CREATE TABLE ITEMS (ID INT AUTO_INCREMENT PRIMARY KEY, 
	NAME VARCHAR(256) UNIQUE NOT NULL);

CREATE TABLE VOTERS (ID INT AUTO_INCREMENT PRIMARY KEY,
	IP VARCHAR(256) NOT NULL UNIQUE);
	
CREATE TABLE RECORDS (RECORDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	VOTEFOR INT NOT NULL,
	VOTEBY INT NOT NULL,
	VOTEROUND INT NOT NULL,
	FOREIGN KEY (VOTEFOR) REFERENCES ITEMS(ID),
	FOREIGN KEY (VOTEBY) REFERENCES VOTERS(ID));
	
CREATE TABLE ROUNDS (ID INT AUTO_INCREMENT PRIMARY KEY,
	STARTAT DATE NOT NULL,
	CURRENT BOOLEAN DEFAULT 1 NOT NULL);